#!/system/bin/sh

echo "ondemand" >  /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
echo "20000" > /sys/devices/system/cpu/cpu0/cpufreq/ondemand/sampling_rate
echo "85" > /sys/devices/system/cpu/cpu0/cpufreq/ondemand/up_threshold
#echo "710400" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
echo "245760" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq




