#!/system/bin/sh
#
# Compcache or backingswap
# idogx@diypda.com
#


BB="logwrapper busybox";


if [ -e /system/bin/log ];
then
    LOGI="log -p i -t Compcache --";
    LOGE="log -p e -t Compcache --";
else
    LOGI=echo;
    LOGE=echo;
fi;


swapimg=/cache/swap.img;
SWAP=/dev/block/ramzswap0;
backingswap=/dev/block/loop7;


if [ ! -e $SWAP ];
then
   if [ -e /system/lib/modules/ramzswap.ko ];
   then
      insmod /system/lib/modules/ramzswap.ko;
   else
      $LOGE "Compache failed loading ramzswap driver!";
   fi;
fi;



if [ -e $swapimg ];
then
    COMPCACHE=Backingswap;
    $LOGI "$swapimg exists, enabling backingswap...";
    rzscontrol $SWAP --backing_swap=$backingswap --memlimit_kb=24480 --init;
else
    COMPCACHE=Compcache;
    rzscontrol $SWAP --disksize_kb=131072 --init;
fi;
    
if [ -b "$SWAP" ];
then
   echo 0 > /proc/sys/vm/drop_caches;
   echo 80 > /proc/sys/vm/swappiness;
   swapon $SWAP;
   if [ $? -eq 0 ];
   then
      $LOGI "$COMPCACHE enabled successfully!";
   else
      $LOGE "$COMPCACHE failed enabling swap on $SWAP";
   fi;
else
   $LOGE "$COMPCACHE failed loading ramzswap driver";
fi;

