#!/system/bin/sh

# Check whether any cpu tuning apps are already installed.
# If not, we'll start our custom daemon.

BUSYBOX="/system/xbin/busybox"
GREP="$BUSYBOX grep"
PACKAGESXML="/data/system/packages.xml"

if $GREP -q "ch.amana.android.cputuner" $PACKAGESXML ; then
	exit 0
fi

if $GREP -q "com.mhuang.overclocking" $PACKAGESXML ; then
	exit 0
fi

if $GREP -q "org.freecoder.widgets.overclock" $PACKAGESXML ; then
	exit 0
fi

if $GREP -q "com.antutu.CpuMasterFree" $PACKAGESXML ; then
	exit 0
fi

busybox mount -o remount,rw /dev/block/mtdblock3 /system

cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq > /system/etc/virtuous_oc/sleep_min_freq

cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq > /system/etc/virtuous_oc/wake_max_freq

echo powersave > /system/etc/virtuous_oc/sleep_governor
echo ondemand > /system/etc/virtuous_oc/sleep_governor

echo performance > /system/etc/virtuous_oc/wake_governor
echo ondemand > /system/etc/virtuous_oc/wake_governor

busybox mount -o remount,ro /dev/block/mtdblock3 /system

##/system/xbin/virtuous_oc


