#!/system/bin/sh

SLEEP=5

if [ -e /data/.battery-calibrated ] ; then
        exit 0
fi

(
while : ; do
        LEVEL=$(cat /sys/class/power_supply/battery/capacity)
        CUR=$(cat /sys/class/power_supply/battery/batt_current)
        if [ "$LEVEL" == "100" ] && [ "$CUR" == "0" ] ; then
                log -p i -t battery-calibration "*** LEVEL: $LEVEL CUR: $CUR***: calibrating..."
                rm -f /data/system/batterystats.bin
                touch /data/.battery-calibrated
                exit 0
        fi
        log -p i -t battery-calibration "*** LEVEL: $LEVEL CUR: $CUR ***: sleeping for $SLEEP s..."
        sleep $SLEEP
done
) &

